### ISSUE TITLE
Highlighted regions

### ISSUE THREAD

**Issue by markusgritsch** [bgrainger/GitBlame#15]
Some regions in the code appear highlighted. What is highlighted seems to be random. Is this a bug or is there some meaning to it?

![highlight](https://cloud.githubusercontent.com/assets/2684183/9299288/b190092e-44ba-11e5-88c9-5f1aed779765.PNG)

**Comment by bgrainger** [comment]
The highlight is the change added in the most recent commit that touched that line. (If the whole line was added, there is a green bar in the left margin instead.)

**Comment by markusgritsch** [comment]
ah, that's nice. Couldn't make sense of it without this explanation, though :)
